//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovai.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Задача> Задача { get; set; }
        public virtual DbSet<КлючАдминестратора> КлючАдминестратора { get; set; }
        public virtual DbSet<МестоРаботника> МестоРаботника { get; set; }
        public virtual DbSet<Направление> Направление { get; set; }
        public virtual DbSet<Роли> Роли { get; set; }
        public virtual DbSet<Сотрудник> Сотрудник { get; set; }
    }
}
