//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kursovai.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудник
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудник()
        {
            this.Задача = new HashSet<Задача>();
            this.Задача1 = new HashSet<Задача>();
        }
    
        public int Ключ { get; set; }
        public int КлючРоль { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public Nullable<int> МестоРаботы { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public Nullable<bool> ПервыйВход { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Задача> Задача { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Задача> Задача1 { get; set; }
        public virtual МестоРаботника МестоРаботника { get; set; }
        public virtual Роли Роли { get; set; }
    }
}
